#include <stdio.h>

int main ()
{
    int i;
    char h = 'h';
    float pi = 3.14159;
    printf("Number [%20i]\n", 42);
    printf("Number [%+0*i]\n", 8, 42);
    i=printf("%05\n", 'A');
    printf("%d",i);
    i=printf("%05c\n", 'A');
    printf("%d",i);
    i=printf("%.5c\n", 'A');
    printf("%d",i);
    i=printf("%-05c\n", 'A');
    printf("%d",i);
    i=printf("% 5c\n", 'A');
    printf("%d",i);
    i=printf("%#5c\n", 'A');
    printf("%d",i);
    i=printf("%+5c\n", 'A');
    printf("%d",i);
    i=printf("%-0#5c\n", 'A');
    printf("%d",i);
    i=printf("%-0+5c\n", 'A');
    printf("%d",i);
    i=printf("%-0# +5c\n", 'A');
    printf("%d",i);
    i=printf("%-10s\n", "Hello");
    printf("%d",i);
    i=printf("%010s\n", "Hello");
    printf("%d",i);
    i=printf("%.10s\n", "HelloWorld");
    printf("%d",i);
    i=printf("%-010s\n", "Hello");
    printf("%d",i);
    i=printf("% 10s\n", "Hello");
    printf("%d",i);
    i=printf("%#10s\n", "Hello");
    printf("%d",i);
    i=printf("%+10s\n", "Hello");
    printf("%d",i);
    i=printf("%-0#10s\n", "Hello");
    printf("%d",i);
    i=printf("%-0+10s\n", "Hello");
    printf("%d",i);
    i=printf("%-0# +10s\n", "Hello");
    printf("%d",i);
    i=printf("%-10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%010p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%.10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%-010p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("% 10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%#10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%+10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%-0#10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%-0+10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%-0# +10p\n", (void*)0x12345678);
    printf("%d",i);
    i=printf("%-10d\n", 123);
    printf("%d",i);
    i=printf("%010d\n", 123);
    printf("%d",i);
    i=printf("%.10d\n", 123);
    printf("%d",i);
    i=printf("%-010d\n", 123);
    printf("%d",i);
    i=printf("%+10d\n", 123);
    printf("%d",i);
    i=printf("% 10d\n", 123);
    printf("%d",i);
    i=printf("%#10d\n", 123);
    printf("%d",i);
    i=printf("%-0+10d\n", 123);
    printf("%d",i);
    i=printf("%-0#10d\n", 123);
    printf("%d",i);
    i=printf("%-0# +10d\n", 123);
    printf("%d",i);
    i=printf("%-10i\n", 456);
    printf("%d",i);
    i=printf("%010i\n", 456);
    printf("%d",i);
    i=printf("%.10i\n", 456);
    printf("%d",i);
    i=printf("%-010i\n", 456);
    printf("%d",i);
    i=printf("%+10i\n", 456);
    printf("%d",i);
    i=printf("% 10i\n", 456);
    printf("%d",i);
    i=printf("%#10i\n", 456);
    printf("%d",i);
    i=printf("%-0+10i\n", 456);
    printf("%d",i);
    i=printf("%-0#10i\n", 456);
    printf("%d",i);
    i=printf("%-0# +10i\n", 456);
    printf("%d",i);
    i=printf("%-10u\n", 789);
    printf("%d",i);
    i=printf("%010u\n", 789);
    printf("%d",i);
    i=printf("%.10u\n", 789);
    printf("%d",i);
    i=printf("%-010u\n", 789);
    printf("%d",i);
    i=printf("%+10u\n", 789);
    printf("%d",i);
    i=printf("% 10u\n", 789);
    printf("%d",i);
    i=printf("%#10u\n", 789);
    printf("%d",i);
    i=printf("%-0+10u\n", 789);
    printf("%d",i);
    i=printf("%-0#10u\n", 789);
    printf("%d",i);
    i=printf("%-0# +10u\n", 789);
    printf("%d",i);
    i=printf("%-10x\n", 0xabc);
    printf("%d",i);
    i=printf("%010x\n", 0xabc);
    printf("%d",i);
    i=printf("%.10x\n", 0xabc);
    printf("%d",i);
    i=printf("%-010x\n", 0xabc);
    printf("%d",i);
    i=printf("%+10x\n", 0xabc);
    printf("%d",i);
    i=printf("% 10x\n", 0xabc);
    printf("%d",i);
    i=printf("%#10x\n", 0xabc);
    printf("%d",i);
    i=printf("%-0+10x\n", 0xabc);
    printf("%d",i);
    i=printf("%-0#10x\n", 0xabc);
    printf("%d",i);
    i=printf("%-0# +10x\n", 0xabc);
    printf("%d",i);
    i=printf("%-10X\n", 0xDEF);
    printf("%d",i);
    i=printf("%010X\n", 0xDEF);
    printf("%d",i);
    i=printf("%.10X\n", 0xDEF);
    printf("%d",i);
    i=printf("%-010X\n", 0xDEF);
    printf("%d",i);
    i=printf("%+10X\n", 0xDEF);
    printf("%d",i);
    i=printf("% 10X\n", 0xDEF);
    printf("%d",i);
}

